export const apiURL = "https://gofitme-backend.herokuapp.com";

export const clothingTypes = [
  "Tops",
  "Pants",
  "Casual Shoes",
  "Watches",
  "Sports Shoes",
  "Handbags",
  "Heels",
  "Sunglasses",
  "Flip Flops",
  "Sandals",
  "Belts",
  "Backpacks",
  "Socks",
  "Formal Shoes",
  "Jeans",
  "Shorts",
  "Flats",
  "Dresses",
  "Earrings",
  "Coats and Jackets",
  "Sweaters",
  "Sweatshirts and Hoodies",
  "Leggings",
  "Skirts",
  "Other",
];

export const colorMap = {
  Black: "#000000",
  White: "#ffffff",
  Blue: "#24a0ed",
  Brown: "#795548",
  Grey: "#D5D8DC",
  Red: "#C0392B",
  Green: "#229954",
  Pink: "#FF99FF",
  "Navy Blue": "#000099",
  Purple: "#673AB7",
  Silver: "#D5DBDB",
  Yellow: "#FFF176",
  Beige: "#E1C699",
  Gold: "#FFD700",
  Maroon: "#800000",
  Orange: "#FF5722",
  Olive: "#9E9D24",
  Cream: "#FFFDD0",
  Charcoal: "#36454f",
  Peach: "#FFE5B4",
  Multicolored: "wutface",
};
